defaults: &defaults
  base_url: https://www.saltedge.com/api/v5
  application:
    app_id: hdN7KhovCxOB7X_WlmMBTKbP5qv16mHoA7cC5zxHTOc
    secret: F9ymHoGvp58-s1zhSVdErWBWTRjPel1FqXgY3NJ8Y_E


development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
